//! Real integration test: wrap `autofde-lab`'s real `autofde_lab.fabric` Typer
//! CLI (a genuine, independently-maintained Python scikit-decide fork,
//! checked in at `playground/autofde-lab` as a git submodule) through
//! `cnv-any`, and run real planners through the real `Gateway`.
//!
//! `examples/autofde_lab_planners/cnv-any.json` is GENERATED by
//! `cnv-any-manifest-pack` (a real ggen pack at
//! `~/ggen-marketplace/packs/cnv-any-manifest-pack`) from
//! `examples/autofde_lab_planners/ontology.ttl` -- run `ggen sync run` in
//! that directory to regenerate it; it is never hand-edited.
//!
//! The always-run tests below only need the manifest and shim script (no
//! Python environment) -- they prove the wrapping itself is correct. The two
//! `#[ignore]`d tests need `playground/autofde-lab`'s real `.venv` synced
//! first (see `examples/autofde_lab_planners/README.md`'s Setup section);
//! they are a named, visible skip by default (Chicago-style: a real
//! collaborator is used when available, never mocked, and the test is
//! explicitly marked absent rather than silently skipped), run them with:
//!
//! ```sh
//! cargo test --test autofde_lab_integration -- --ignored
//! ```

use clap_noun_verb_any::wrap;
use clap_noun_verb_deploy::{AdmitValidated, Gateway};
use std::path::PathBuf;

fn example_paths() -> (PathBuf, PathBuf) {
    let example = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("examples/autofde_lab_planners");
    (example.join("autofde-lab-fabric.sh"), example.join("cnv-any.json"))
}

#[test]
fn wrap_loads_the_real_autofde_lab_fabric_manifest() {
    // Arrange / Act
    let (executable, manifest) = example_paths();
    let wrapped = wrap(executable.into_os_string(), &manifest)
        .expect("wrap the real autofde-lab-fabric.sh shim with its real ggen-generated manifest");

    // Assert: the manifest's 5 one-shot commands are all present and callable.
    // Every command's ggen-emitted path is ["fabric", <verb>] -- schema-pack
    // always groups commands under a real cnv:Noun.
    let schema = wrapped.deploy().schema();
    assert_eq!(schema.name, "autofde-lab-fabric");
    let verbs: Vec<&str> = schema
        .commands
        .iter()
        .map(|command| {
            assert_eq!(command.path[0], "fabric");
            command.path[1].as_str()
        })
        .collect();
    for expected in ["catalog", "match", "solve", "cache-stats", "cache-hotset"] {
        assert!(verbs.contains(&expected), "missing command {expected} in {verbs:?}");
    }
    assert!(schema.commands.iter().all(|command| command.callable));
}

#[test]
fn wrap_builds_a_real_solve_invocation_selecting_any_registered_planner() {
    // Arrange
    let (executable, manifest) = example_paths();
    let wrapped = wrap(executable.into_os_string(), &manifest).expect("wrap real shim+manifest");

    // Act: build an invocation naming an arbitrary planner -- "Astar" here,
    // but this is a plain string value; any of the 46+ solver names in
    // autofde-lab's real `pyproject.toml` `[project.entry-points."autofde_lab.solvers"]`
    // table works identically, with zero manifest or Rust changes.
    let mut arguments = serde_json::Map::new();
    arguments.insert("domain".to_owned(), serde_json::json!("PDDLDomain"));
    arguments.insert("solver".to_owned(), serde_json::json!("Astar"));
    // Keys here must be the manifest's external (long-flag) names, not the
    // internal `id` -- `max-steps`, not `max_steps` -- matching how an
    // MCP/HTTP caller sees this tool's real JSON schema property names.
    arguments.insert("max-steps".to_owned(), serde_json::json!("50"));
    // The tool name is the ggen-emitted path joined with "__" (CommandSchema::tool_name).
    let invocation = wrapped
        .deploy()
        .schema()
        .build_invocation("fabric__solve", &arguments)
        .expect("manifest admits a validated solve invocation naming any registered planner");

    // Assert: real argv reconstruction, no process spawned yet. The leading
    // "fabric" token is the ggen-emitted noun the shim strips before
    // forwarding to the real `autofde_lab.fabric` CLI (see
    // autofde-lab-fabric.sh). Argument order follows the manifest's own
    // (ggen-emitted, position-then-field-ordered) argument list, not
    // insertion order into this test's JSON map: `max-steps`/`solver` (both
    // position 0, alphabetical by field) before the positional `domain`.
    assert_eq!(
        invocation.args,
        vec![
            "fabric".to_owned(),
            "solve".to_owned(),
            "--max-steps".to_owned(),
            "50".to_owned(),
            "--solver".to_owned(),
            "Astar".to_owned(),
            "PDDLDomain".to_owned(),
        ]
    );
}

#[test]
#[ignore = "requires playground/autofde-lab's real .venv; see examples/autofde_lab_planners/README.md Setup"]
fn real_catalog_call_lists_astar_and_ff_among_46_plus_registered_planners() {
    // Arrange
    let (executable, manifest) = example_paths();
    let wrapped = wrap(executable.into_os_string(), &manifest).expect("wrap real shim+manifest");
    let invocation = wrapped
        .deploy()
        .schema()
        .build_invocation("fabric__catalog", &serde_json::Map::new())
        .expect("catalog takes no arguments");

    // Act: a real subprocess, a real Python interpreter, a real autofde-lab
    // import -- no mock anywhere in this path.
    let (_deploy, executor) = wrapped.into_parts();
    let gateway = Gateway::new("autofde-lab-fabric", executor, AdmitValidated);
    let record = gateway.execute(invocation).expect("real catalog call succeeds");

    // Assert
    assert!(record.execution.success(), "stderr: {}", record.execution.stderr);
    let catalog: serde_json::Value =
        serde_json::from_str(&record.execution.stdout).expect("real JSON catalog output");
    let solvers = catalog["solvers"].as_array().expect("catalog.solvers is a real array");
    assert!(solvers.len() >= 40, "expected 40+ registered solvers, got {}", solvers.len());
    let names: Vec<&str> = solvers.iter().filter_map(serde_json::Value::as_str).collect();
    assert!(names.contains(&"Astar"));
    assert!(names.contains(&"FF"));
}

#[test]
#[ignore = "requires playground/autofde-lab's real .venv; see examples/autofde_lab_planners/README.md Setup"]
fn real_astar_solve_over_a_real_pddl_blocksworld_fixture_produces_a_receipted_trajectory() {
    // Arrange: the real PDDL fixtures autofde_lab's own
    // reasoning/planner_federation.py docstring names as empirically
    // verified working with Astar's defaults.
    let (executable, manifest) = example_paths();
    let wrapped = wrap(executable.into_os_string(), &manifest).expect("wrap real shim+manifest");
    let mut arguments = serde_json::Map::new();
    arguments.insert("domain".to_owned(), serde_json::json!("PDDLDomain"));
    arguments.insert("solver".to_owned(), serde_json::json!("Astar"));
    arguments.insert(
        "domain-arguments".to_owned(),
        serde_json::json!(concat!(
            "{\"domain_path\": \"tests/domains/python/pddl_domains/blocks/domain.pddl\", ",
            "\"problem_path\": \"tests/domains/python/pddl_domains/blocks/probBLOCKS-3-0.pddl\"}"
        )),
    );
    arguments.insert("max-steps".to_owned(), serde_json::json!("50"));
    let invocation = wrapped
        .deploy()
        .schema()
        .build_invocation("fabric__solve", &arguments)
        .expect("manifest admits a validated solve invocation");

    // Act: a real Astar solve, over a real PDDL blocksworld instance, through
    // a real Python subprocess.
    let (_deploy, executor) = wrapped.into_parts();
    let gateway = Gateway::new("autofde-lab-fabric", executor, AdmitValidated);
    let record = gateway.execute(invocation).expect("real Astar solve succeeds");

    // Assert. autofde-lab's own PDDL domain parser logs real `[info] Parsing
    // ...` lines to stdout ahead of the Typer CLI's final `typer.echo(json.dumps(...,
    // indent=2))` payload -- a real, true-to-life "any language" wrinkle
    // (plenty of real CLIs interleave log noise and structured output on the
    // same stream), not something this test should paper over by trusting
    // the whole stdout blob is pure JSON. A naive first-`{` search is also
    // wrong here: log lines can themselves contain a literal `{` (this
    // domain logs Python `frozenset({...})` reprs). `json.dumps(indent=2)`
    // always puts its opening brace alone on its own line, so find the
    // LAST such line instead.
    assert!(record.execution.success(), "stderr: {}", record.execution.stderr);
    let json_start = record
        .execution
        .stdout
        .match_indices("\n{\n")
        .last()
        .map(|(index, _)| index + 1)
        .or_else(|| record.execution.stdout.starts_with("{\n").then_some(0))
        .expect("stdout contains a json.dumps(indent=2) payload after any log preamble");
    let trajectory: serde_json::Value =
        serde_json::from_str(&record.execution.stdout[json_start..])
            .expect("real JSON trajectory output");
    assert_eq!(trajectory["terminal"], serde_json::json!(true));
    assert!(
        trajectory["trajectory_sha256"].as_str().is_some_and(|hash| hash.len() == 64),
        "expected a real 64-char sha256 receipt, got {:?}",
        trajectory["trajectory_sha256"]
    );
}
